### ISSUE TITLE
Problems with mobile internet and network

### ISSUE THREAD

**Issue by rkadiy** [washinson/android_device_meizu_m3s#2]
1) Mobile Internet is switched on from several attempts and not always. Also mobile internet is very slow. 
2) When the Internet is turned off, exclamation marks are displayed in the network status bar
![image](https://user-images.githubusercontent.com/34950762/60395238-58658480-9b39-11e9-846b-c6ded490929f.png)
3) I will also note the lower phone autonomy compared to stock Flyme firmware.

**Comment by washinson** [comment]
1. First sim has lte, second sim has 2g only. It is bug cyanogenmod 12.1. I can not fix it. 
2. Exclamation marks says that mobile network is turned off. It is cyanogemmod feature. Not a bug.
3. Are google services installed? It is hard to predict a problem reason...

**Comment by rkadiy** [comment]
SIM card with internet installed in the first slot

**Comment by washinson** [comment]
Is 3g or lte selected? Is mobile internet slow with it?

**Comment by rkadiy** [comment]
I corrected the settings for the APN and now it worked

**Comment by washinson** [comment]
Battery issue will fixed in next release. I think tnat incorrect battery capacity in config
